import * as vscode from "vscode";
const nativeComponentList = [
  "view",
  "scroll-view",
  "swiper",
  "movable-view",
  "cover-view",
  "icon",
  "text",
  "block",
  "slot",
  "i",
  "rich-text",
  "progress",
  "button",
  "checkbox",
  "form",
  "input",
  "label",
  "picker",
  "picker-view",
  "radio",
  "slider",
  "switch",
  "textarea",
  "navigator",
  "audio",
  "camera",
  "image",
  "live-player",
  "video",
  "map",
  "canvas",
  "open-data",
  "web-view",
  "ad",
  "official-account",
  "editor",
  "swiper-item",
  "movable-area",
  "cover-image",
  "checkbox-group",
  "radio-group",
  "functional-page-navigator",
];
const config = vscode.workspace.getConfiguration("annil");
const userSetting: string[] = config.get("excludeTags") || [];

export const excludeTags = nativeComponentList.concat(userSetting);
